/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationIdRouteImport } from './routes/location.$id'
import { Route as ApiPublicCronScrapeEventsRouteImport } from './routes/api/public/cron/scrape-events'
import { Route as ApiPublicAdminSyncStartupMapRouteImport } from './routes/api/public/admin/sync-startup-map'

const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationIdRoute = LocationIdRouteImport.update({
  id: '/location/$id',
  path: '/location/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronScrapeEventsRoute =
  ApiPublicCronScrapeEventsRouteImport.update({
    id: '/api/public/cron/scrape-events',
    path: '/api/public/cron/scrape-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminSyncStartupMapRoute =
  ApiPublicAdminSyncStartupMapRouteImport.update({
    id: '/api/public/admin/sync-startup-map',
    path: '/api/public/admin/sync-startup-map',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/location/$id': typeof LocationIdRoute
  '/api/public/admin/sync-startup-map': typeof ApiPublicAdminSyncStartupMapRoute
  '/api/public/cron/scrape-events': typeof ApiPublicCronScrapeEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/location/$id': typeof LocationIdRoute
  '/api/public/admin/sync-startup-map': typeof ApiPublicAdminSyncStartupMapRoute
  '/api/public/cron/scrape-events': typeof ApiPublicCronScrapeEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/location/$id': typeof LocationIdRoute
  '/api/public/admin/sync-startup-map': typeof ApiPublicAdminSyncStartupMapRoute
  '/api/public/cron/scrape-events': typeof ApiPublicCronScrapeEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/login'
    | '/onboarding'
    | '/opportunities'
    | '/location/$id'
    | '/api/public/admin/sync-startup-map'
    | '/api/public/cron/scrape-events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/login'
    | '/onboarding'
    | '/opportunities'
    | '/location/$id'
    | '/api/public/admin/sync-startup-map'
    | '/api/public/cron/scrape-events'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/login'
    | '/onboarding'
    | '/opportunities'
    | '/location/$id'
    | '/api/public/admin/sync-startup-map'
    | '/api/public/cron/scrape-events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  LocationIdRoute: typeof LocationIdRoute
  ApiPublicAdminSyncStartupMapRoute: typeof ApiPublicAdminSyncStartupMapRoute
  ApiPublicCronScrapeEventsRoute: typeof ApiPublicCronScrapeEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/$id': {
      id: '/location/$id'
      path: '/location/$id'
      fullPath: '/location/$id'
      preLoaderRoute: typeof LocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape-events': {
      id: '/api/public/cron/scrape-events'
      path: '/api/public/cron/scrape-events'
      fullPath: '/api/public/cron/scrape-events'
      preLoaderRoute: typeof ApiPublicCronScrapeEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/sync-startup-map': {
      id: '/api/public/admin/sync-startup-map'
      path: '/api/public/admin/sync-startup-map'
      fullPath: '/api/public/admin/sync-startup-map'
      preLoaderRoute: typeof ApiPublicAdminSyncStartupMapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  LocationIdRoute: LocationIdRoute,
  ApiPublicAdminSyncStartupMapRoute: ApiPublicAdminSyncStartupMapRoute,
  ApiPublicCronScrapeEventsRoute: ApiPublicCronScrapeEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
