/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MyHubRouteImport } from './routes/my-hub'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MatchRouteImport } from './routes/match'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationIdRouteImport } from './routes/location.$id'
import { Route as ApiPublicCronScrapeEventsRouteImport } from './routes/api/public/cron/scrape-events'
import { Route as ApiPublicAdminSyncStartupMapRouteImport } from './routes/api/public/admin/sync-startup-map'
import { Route as ApiPublicAdminFixStartupMapWebsitesRouteImport } from './routes/api/public/admin/fix-startup-map-websites'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHubRoute = MyHubRouteImport.update({
  id: '/my-hub',
  path: '/my-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationIdRoute = LocationIdRouteImport.update({
  id: '/location/$id',
  path: '/location/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronScrapeEventsRoute =
  ApiPublicCronScrapeEventsRouteImport.update({
    id: '/api/public/cron/scrape-events',
    path: '/api/public/cron/scrape-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminSyncStartupMapRoute =
  ApiPublicAdminSyncStartupMapRouteImport.update({
    id: '/api/public/admin/sync-startup-map',
    path: '/api/public/admin/sync-startup-map',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminFixStartupMapWebsitesRoute =
  ApiPublicAdminFixStartupMapWebsitesRouteImport.update({
    id: '/api/public/admin/fix-startup-map-websites',
    path: '/api/public/admin/fix-startup-map-websites',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/ecosystem': typeof EcosystemRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/messages': typeof MessagesRoute
  '/my-hub': typeof MyHubRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/presentation': typeof PresentationRoute
  '/settings': typeof SettingsRoute
  '/location/$id': typeof LocationIdRoute
  '/api/public/admin/fix-startup-map-websites': typeof ApiPublicAdminFixStartupMapWebsitesRoute
  '/api/public/admin/sync-startup-map': typeof ApiPublicAdminSyncStartupMapRoute
  '/api/public/cron/scrape-events': typeof ApiPublicCronScrapeEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/ecosystem': typeof EcosystemRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/messages': typeof MessagesRoute
  '/my-hub': typeof MyHubRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/presentation': typeof PresentationRoute
  '/settings': typeof SettingsRoute
  '/location/$id': typeof LocationIdRoute
  '/api/public/admin/fix-startup-map-websites': typeof ApiPublicAdminFixStartupMapWebsitesRoute
  '/api/public/admin/sync-startup-map': typeof ApiPublicAdminSyncStartupMapRoute
  '/api/public/cron/scrape-events': typeof ApiPublicCronScrapeEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/ecosystem': typeof EcosystemRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/messages': typeof MessagesRoute
  '/my-hub': typeof MyHubRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/presentation': typeof PresentationRoute
  '/settings': typeof SettingsRoute
  '/location/$id': typeof LocationIdRoute
  '/api/public/admin/fix-startup-map-websites': typeof ApiPublicAdminFixStartupMapWebsitesRoute
  '/api/public/admin/sync-startup-map': typeof ApiPublicAdminSyncStartupMapRoute
  '/api/public/cron/scrape-events': typeof ApiPublicCronScrapeEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/ecosystem'
    | '/events'
    | '/login'
    | '/match'
    | '/messages'
    | '/my-hub'
    | '/onboarding'
    | '/opportunities'
    | '/presentation'
    | '/settings'
    | '/location/$id'
    | '/api/public/admin/fix-startup-map-websites'
    | '/api/public/admin/sync-startup-map'
    | '/api/public/cron/scrape-events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/ecosystem'
    | '/events'
    | '/login'
    | '/match'
    | '/messages'
    | '/my-hub'
    | '/onboarding'
    | '/opportunities'
    | '/presentation'
    | '/settings'
    | '/location/$id'
    | '/api/public/admin/fix-startup-map-websites'
    | '/api/public/admin/sync-startup-map'
    | '/api/public/cron/scrape-events'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/ecosystem'
    | '/events'
    | '/login'
    | '/match'
    | '/messages'
    | '/my-hub'
    | '/onboarding'
    | '/opportunities'
    | '/presentation'
    | '/settings'
    | '/location/$id'
    | '/api/public/admin/fix-startup-map-websites'
    | '/api/public/admin/sync-startup-map'
    | '/api/public/cron/scrape-events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  EcosystemRoute: typeof EcosystemRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  MatchRoute: typeof MatchRoute
  MessagesRoute: typeof MessagesRoute
  MyHubRoute: typeof MyHubRoute
  OnboardingRoute: typeof OnboardingRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PresentationRoute: typeof PresentationRoute
  SettingsRoute: typeof SettingsRoute
  LocationIdRoute: typeof LocationIdRoute
  ApiPublicAdminFixStartupMapWebsitesRoute: typeof ApiPublicAdminFixStartupMapWebsitesRoute
  ApiPublicAdminSyncStartupMapRoute: typeof ApiPublicAdminSyncStartupMapRoute
  ApiPublicCronScrapeEventsRoute: typeof ApiPublicCronScrapeEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-hub': {
      id: '/my-hub'
      path: '/my-hub'
      fullPath: '/my-hub'
      preLoaderRoute: typeof MyHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/$id': {
      id: '/location/$id'
      path: '/location/$id'
      fullPath: '/location/$id'
      preLoaderRoute: typeof LocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape-events': {
      id: '/api/public/cron/scrape-events'
      path: '/api/public/cron/scrape-events'
      fullPath: '/api/public/cron/scrape-events'
      preLoaderRoute: typeof ApiPublicCronScrapeEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/sync-startup-map': {
      id: '/api/public/admin/sync-startup-map'
      path: '/api/public/admin/sync-startup-map'
      fullPath: '/api/public/admin/sync-startup-map'
      preLoaderRoute: typeof ApiPublicAdminSyncStartupMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/fix-startup-map-websites': {
      id: '/api/public/admin/fix-startup-map-websites'
      path: '/api/public/admin/fix-startup-map-websites'
      fullPath: '/api/public/admin/fix-startup-map-websites'
      preLoaderRoute: typeof ApiPublicAdminFixStartupMapWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  EcosystemRoute: EcosystemRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  MatchRoute: MatchRoute,
  MessagesRoute: MessagesRoute,
  MyHubRoute: MyHubRoute,
  OnboardingRoute: OnboardingRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PresentationRoute: PresentationRoute,
  SettingsRoute: SettingsRoute,
  LocationIdRoute: LocationIdRoute,
  ApiPublicAdminFixStartupMapWebsitesRoute:
    ApiPublicAdminFixStartupMapWebsitesRoute,
  ApiPublicAdminSyncStartupMapRoute: ApiPublicAdminSyncStartupMapRoute,
  ApiPublicCronScrapeEventsRoute: ApiPublicCronScrapeEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
